<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paginacaoProximo</name>
   <tag></tag>
   <elementGuidId>d4e82526-4a25-44ab-aefa-1201819d718a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-chevron-right.mdi-24px</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/div/div[3]/div/div/div[3]/div[2]/div/nav/a[2]/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-chevron-right mdi-24px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm&quot;]/div[@class=&quot;b-table&quot;]/div[@class=&quot;top level&quot;]/div[@class=&quot;level-right&quot;]/div[@class=&quot;level-item&quot;]/nav[@class=&quot;pagination&quot;]/a[@class=&quot;pagination-link pagination-next&quot;]/span[@class=&quot;icon&quot;]/i[@class=&quot;mdi mdi-chevron-right mdi-24px&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div/div[3]/div/div/div[3]/div[2]/div/nav/a[2]/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a[2]/span/i</value>
   </webElementXpaths>
</WebElementEntity>
